[package]
name = "wasm-provider"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
log = { workspace = true }
shared-types = { path = "../shared-types" }
wasmtime = "41"
wasmtime-wasi = "41.0.3"

[lib]
path = "src/lib.rs"